apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: demo.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: java-service-api
                port:
                  number: 80
          - path: /web
            pathType: Prefix
            backend:
              service:
                name: java-service-web
                port:
                  number: 80
